[package]
name = "command-proxy"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-rt = "2.11.0"
actix-web =  "4.11.0"
actix-web-httpauth = "0.8.2"
actix-settings = "0.9.0"
serde = "1.0.106"
toml = "0.9.6"
log = "0.4.28"
log4rs = "1.4.0"
clap = { version = "*", features = ["derive"] }
