name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose -r
    - name: Run tests
      run: cargo test --verbose -r
    - name: get cargo manifest
      id: cargo_manifest
      run: echo ${{ fromJSON(`cargo read-manifest`) }} >> $GITHUB_OUTPUT
    - name: get version
      run: echo ${{ fromJSON(steps.cargo_manifest.outputs).version }}
    - name: Publish built binary to GitHub releases
      run: |
        gh release create --generate-notes ./target/release/command-proxy
