name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write
  workflows: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose -r
    - name: Run tests
      run: cargo test --verbose -r
    - name: Publish built binary to GitHub releases
      run: |
        gh release create --generate-notes ./target/release/command-proxy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
