name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose -r
    - name: Run tests
      run: cargo test --verbose -r
    - name: get cargo manifest
      id: prog_version
      run: echo version=$(cargo read-manifest | jq .version -r) >> $GITHUB_OUTPUT
    - name: Publish built binary to GitHub releases
      run: |
        gh release create ${{ steps.prog_version.outputs.version }} --generate-notes ./target/release/command-proxy
      env:
        GH_TOKEN: ${{ github.token }}
